project_name: agg-warning-query

builds:
  - main: ./main/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows

archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: binary

sign:
  artifacts: none

release:
  github:
    owner: TerrexTech
    name: agg-warning-query

changelog:
  sort: asc
  filters:
    exclude:
      - '^bors:'
      - '^docs:'
      - typo

dockers:
  - image: terrextech/agg-warning-query
    binary: agg-warning-query
    dockerfile: Dockerfile_ci
    goos: linux
    goarch: amd64
    tag_templates:
      - "{{ .Tag }}"
      - latest
    extra_files:
      - .env
